# Generated by Django 4.2.9 on 2024-01-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("f_name", models.CharField(max_length=32, verbose_name="Имя")),
                ("s_name", models.CharField(max_length=32, verbose_name="Фамилимя")),
                ("age", models.IntegerField(max_length=3, verbose_name="Возраст")),
                ("job", models.CharField(max_length=64, verbose_name="Должность")),
            ],
        ),
    ]
