# Generated by Django 4.2.9 on 2024-01-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("First_App", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="age",
            field=models.IntegerField(verbose_name="Возраст"),
        ),
    ]
