# Generated by Django 4.2.9 on 2024-01-12 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("First_App", "0002_alter_person_age"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={"verbose_name": "Человек", "verbose_name_plural": "Люди"},
        ),
    ]
