# Generated by Django 4.2.9 on 2024-01-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("First_App", "0003_alter_person_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vacancies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="Имя")),
                ("key_skills", models.CharField(max_length=128, verbose_name="Умения")),
                ("salary_from", models.IntegerField(verbose_name="Зарплата от")),
                ("salary_to", models.IntegerField(verbose_name="Зарплата до")),
                (
                    "salary_currency",
                    models.CharField(max_length=32, verbose_name="Валюта"),
                ),
                ("area_name", models.CharField(max_length=32, verbose_name="Место")),
                ("published_at", models.DateTimeField(verbose_name="Публикация")),
            ],
            options={
                "verbose_name": "Вакансия",
                "verbose_name_plural": "Вакансии",
            },
        ),
        migrations.DeleteModel(
            name="Person",
        ),
    ]
