# Generated by Django 4.2.9 on 2024-01-15 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("First_App", "0004_vacancies_delete_person"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vacancies",
            options={"verbose_name": "Вакансии", "verbose_name_plural": "Вакансии"},
        ),
    ]
