# Generated by Django 4.2.7 on 2024-01-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='demand', verbose_name='Таблица')),
                ('text', models.TextField(default=None, verbose_name='Текст')),
                ('graph_left', models.ImageField(default=None, upload_to='demand', verbose_name='График №2')),
                ('graph_right', models.ImageField(default=None, upload_to='demand', verbose_name='График №1')),
            ],
        ),
        migrations.CreateModel(
            name='Geography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='demand', verbose_name='Таблица')),
                ('text', models.TextField(default=None, verbose_name='Текст')),
                ('graph_left', models.ImageField(default=None, upload_to='demand', verbose_name='График №2')),
                ('graph_right', models.ImageField(default=None, upload_to='demand', verbose_name='График №1')),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default=None, verbose_name='Текст')),
                ('image', models.ImageField(default=None, upload_to='home', verbose_name='img')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='skills', verbose_name='Таблица')),
                ('graph', models.ImageField(default=None, upload_to='skills', verbose_name='График')),
                ('text', models.TextField(default=None, verbose_name='Текст')),
            ],
        ),
        migrations.DeleteModel(
            name='LastVacancyModel',
        ),
    ]
